JwtToken:
    key: "JWT_SECRET_KEY_VU_THANH_TUNG_1721991"
    expired-time: 720000


spring:
    application:
        name: ecommerce
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: tung@172
        url: jdbc:mysql://localhost:3306/ecommerce

    jpa:
        hibernate:
            naming:
                implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"
                physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
        properties:
            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                dialect: org.hibernate.dialect.MySQLDialect
                enable_lazy_load_no_trans: true
                format_sql: true
                show_sql: true
            eclipselink:
                metadata-source:
                    properties:
                        file: constant, message, validator-en
        show-sql: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 50MB
            max-request-size: 50MB
            file-size-threshold: 10MB
server:
    port: 8088
logging:
    level:
        root: DEBUG


upload:
    User:
        location: /Users
    Product:
        location: /Products
